toolbar:
  - undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link forecolor backcolor | fullscreen emoticons | preview
plugins:
  - table
  - fullscreen
  - colorpicker
  - textcolor
  - emoticons
  - preview
  - link
  
menubar: false

statusbar: false